# Generated by Django 4.2.30 on 2026-05-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='remaining_calls',
            field=models.IntegerField(blank=True, help_text='null表示无限制', null=True, verbose_name='剩余调用次数'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='total_calls',
            field=models.IntegerField(default=0, verbose_name='总调用次数'),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='input_tokens',
            field=models.IntegerField(default=0, verbose_name='输入Token'),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='output_tokens',
            field=models.IntegerField(default=0, verbose_name='输出Token'),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='total_tokens',
            field=models.IntegerField(default=0, verbose_name='总Token'),
        ),
    ]
