# Generated by Django 4.2.30 on 2026-05-05 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_bill"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=32, unique=True, verbose_name="卡密"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="面值"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("unused", "未使用"), ("used", "已使用")],
                        default="unused",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "batch_no",
                    models.CharField(
                        blank=True,
                        help_text="批量生成时的批次标识",
                        max_length=50,
                        verbose_name="批次号",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="使用时间"
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_cards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "卡密",
                "verbose_name_plural": "卡密",
                "db_table": "card_passwords",
                "ordering": ("-created_at",),
            },
        ),
    ]
