# Generated by Django 6.0.4 on 2026-05-05 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_cardpassword"),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rebate_type",
                    models.CharField(
                        choices=[
                            ("first", "首次返利"),
                            ("every", "每次返利"),
                            ("upgrade", "满X人升级为每次返利"),
                        ],
                        default="first",
                        max_length=20,
                        verbose_name="返利方式",
                    ),
                ),
                (
                    "rebate_ratio",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.1,
                        help_text="如0.10表示10%",
                        max_digits=5,
                        verbose_name="返利比例",
                    ),
                ),
                (
                    "upgrade_threshold",
                    models.IntegerField(
                        default=10,
                        help_text="仅upgrade类型有效",
                        verbose_name="升级所需邀请人数",
                    ),
                ),
                (
                    "reward_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="单笔返利金额达到此值需审核",
                        max_digits=10,
                        verbose_name="返利审核阈值",
                    ),
                ),
                (
                    "rebate_description",
                    models.TextField(
                        blank=True,
                        default="邀请好友注册并充值，您可获得返利奖励。",
                        verbose_name="返利说明",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "邀请返利配置",
                "verbose_name_plural": "邀请返利配置",
                "db_table": "invite_config",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="invite_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=16,
                null=True,
                unique=True,
                verbose_name="邀请码",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invitees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="邀请人",
            ),
        ),
        migrations.CreateModel(
            name="InviteReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recharge_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="充值金额"
                    ),
                ),
                (
                    "reward_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="返利金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_reward_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="被邀请人",
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_rewards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="邀请人",
                    ),
                ),
            ],
            options={
                "verbose_name": "邀请返利记录",
                "verbose_name_plural": "邀请返利记录",
                "db_table": "invite_rewards",
                "ordering": ("-created_at",),
            },
        ),
    ]
