# Generated by Django 4.2.30 on 2026-05-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_inviteconfig_user_invite_code_user_invited_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='启用邮箱服务')),
                ('smtp_host', models.CharField(blank=True, default='', max_length=200, verbose_name='SMTP 服务器')),
                ('smtp_port', models.IntegerField(default=465, verbose_name='SMTP 端口')),
                ('use_ssl', models.BooleanField(default=True, help_text='465 端口建议 SSL；587 端口建议 TLS（关闭 SSL）', verbose_name='使用 SSL')),
                ('use_tls', models.BooleanField(default=False, verbose_name='使用 TLS (STARTTLS)')),
                ('smtp_user', models.CharField(blank=True, default='', max_length=200, verbose_name='SMTP 用户名')),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255, verbose_name='SMTP 密码/授权码')),
                ('from_email', models.CharField(blank=True, default='', help_text='可与 smtp_user 不同；通常填同一个邮箱地址', max_length=200, verbose_name='发件人邮箱')),
                ('from_name', models.CharField(blank=True, default='uniTokenHub', max_length=200, verbose_name='发件人名称')),
                ('code_expire_minutes', models.IntegerField(default=5, verbose_name='验证码有效期（分钟）')),
                ('code_resend_seconds', models.IntegerField(default=60, verbose_name='验证码重发间隔（秒）')),
                ('daily_limit_per_email', models.IntegerField(default=10, verbose_name='单邮箱每日发送上限')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '邮箱配置',
                'verbose_name_plural': '邮箱配置',
                'db_table': 'email_config',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='邮箱')),
                ('code', models.CharField(max_length=10, verbose_name='验证码')),
                ('purpose', models.CharField(choices=[('register', '注册'), ('reset_password', '重置密码')], default='register', max_length=32, verbose_name='用途')),
                ('is_used', models.BooleanField(default=False, verbose_name='已使用')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
                'db_table': 'email_verify_codes',
                'ordering': ('-created_at',),
            },
        ),
    ]
