# Generated by Django 4.2.30 on 2026-05-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_email_config_and_verify_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='cached_tokens',
            field=models.IntegerField(default=0, verbose_name='缓存命中Token'),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='费用(元)'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='交易金额'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='balance',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='交易后余额'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='余额'),
        ),
    ]
