# Generated by Django 6.0.4 on 2026-05-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_add_token_cost_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="amount",
            field=models.DecimalField(
                decimal_places=6, max_digits=12, verbose_name="交易金额"
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="balance",
            field=models.DecimalField(
                decimal_places=6, max_digits=12, verbose_name="交易后余额"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.DecimalField(
                decimal_places=6, default=0, max_digits=12, verbose_name="余额"
            ),
        ),
    ]
