# Generated by Django 4.2.30 on 2026-05-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_package_redirect_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='交易金额'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='balance',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='交易后余额'),
        ),
        migrations.AlterField(
            model_name='rechargepackage',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, help_text='额外赠送的金额', max_digits=10, verbose_name='赠送金额'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='余额'),
        ),
    ]
