# Generated by Django 4.2.30 on 2026-05-10 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_page_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=128, verbose_name='会话标识')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('path', models.CharField(db_index=True, max_length=500, verbose_name='访问路径')),
                ('referer', models.URLField(blank=True, default='', verbose_name='来源页')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='UA信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='访问时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '页面访问记录',
                'verbose_name_plural': '页面访问记录',
                'db_table': 'page_views',
                'ordering': ('-created_at',),
            },
        ),
    ]
