# Generated by Django 6.0.4 on 2026-05-11 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_bill_amount_alter_bill_balance_and_more"),
        ("users", "0012_add_alert_config"),
    ]

    operations = []
