# Generated by Django 6.0.4 on 2026-05-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_merge_20260511_1035"),
    ]

    operations = [
        migrations.AddField(
            model_name="usagelog",
            name="profit",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                help_text="用户支付费用与上游成本的差额",
                max_digits=12,
                verbose_name="利润(元)",
            ),
        ),
        migrations.AddField(
            model_name="usagelog",
            name="upstream_cost",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                help_text="实际支付给上游供应商的费用",
                max_digits=12,
                verbose_name="上游成本(元)",
            ),
        ),
        migrations.AlterField(
            model_name="pageview",
            name="created_at",
            field=models.DateTimeField(db_index=True, verbose_name="访问时间"),
        ),
    ]
