# Generated by Django 4.2.30 on 2026-05-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_add_cost_profit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='type',
            field=models.CharField(choices=[('recharge', '充值'), ('consume', '消费'), ('refund', '退款'), ('bonus', '赠送')], max_length=20, verbose_name='交易类型'),
        ),
    ]
