# Generated by Django 6.0.4 on 2026-05-11 12:01

import apps.image_gen.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_code",
                    models.CharField(
                        default="gpt-image-2", max_length=100, verbose_name="模型代码"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("generate", "生成"), ("edit", "编辑")],
                        default="generate",
                        max_length=20,
                        verbose_name="模式",
                    ),
                ),
                ("prompt", models.TextField(verbose_name="提示词")),
                (
                    "size",
                    models.CharField(
                        default="auto", max_length=20, verbose_name="尺寸"
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        default="auto", max_length=20, verbose_name="质量"
                    ),
                ),
                ("n", models.IntegerField(default=1, verbose_name="生成数量")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "生成中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=10,
                        verbose_name="费用(元)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_generations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "图像生成记录",
                "verbose_name_plural": "图像生成记录",
                "db_table": "image_generations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.image_gen.models.image_upload_path,
                        verbose_name="图片",
                    ),
                ),
                (
                    "revised_prompt",
                    models.TextField(
                        blank=True, default="", verbose_name="修改后的提示词"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="image_gen.imagegeneration",
                        verbose_name="生成记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "生成图片",
                "verbose_name_plural": "生成图片",
                "db_table": "generated_images",
                "ordering": ["id"],
            },
        ),
    ]
