/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CodeBlock: typeof import('./components/CodeBlock.vue')['default']
    CookieConsent: typeof import('./components/CookieConsent.vue')['default']
    ImageUpload: typeof import('./components/ImageUpload.vue')['default']
    LangToggle: typeof import('./components/LangToggle.vue')['default']
    RechargeDialog: typeof import('./components/RechargeDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeoMeta: typeof import('./components/SeoMeta.vue')['default']
    TagsView: typeof import('./components/admin/TagsView.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
  }
}
