# Generated by Django 4.2.30 on 2026-05-04 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10, verbose_name='方法')),
                ('path', models.CharField(max_length=500, verbose_name='路径')),
                ('request_headers', models.JSONField(default=dict, verbose_name='请求头')),
                ('request_params', models.JSONField(default=dict, verbose_name='请求参数')),
                ('request_body', models.TextField(blank=True, verbose_name='请求体')),
                ('response_status', models.IntegerField(default=0, verbose_name='响应状态')),
                ('response_body', models.TextField(blank=True, verbose_name='响应体')),
                ('response_time', models.IntegerField(default=0, verbose_name='响应时间(ms)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='访问时间')),
            ],
            options={
                'verbose_name': 'API访问记录',
                'verbose_name_plural': 'API访问记录',
                'db_table': 'api_access_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APICategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'API分类',
                'verbose_name_plural': 'API分类',
                'db_table': 'api_categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='API名称')),
                ('path', models.CharField(max_length=500, verbose_name='请求路径')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=10, verbose_name='请求方法')),
                ('description', models.TextField(blank=True, verbose_name='API描述')),
                ('doc_url', models.URLField(blank=True, verbose_name='文档链接')),
                ('target_url', models.URLField(blank=True, help_text='实际调用的API地址', verbose_name='目标URL')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='自定义请求头')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='默认参数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_public', models.BooleanField(default=True, help_text='公开API无需认证即可调用', verbose_name='是否公开')),
                ('rate_limit', models.IntegerField(default=60, verbose_name='速率限制(次/分钟)')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='单价(元/次)')),
                ('timeout', models.IntegerField(default=30, verbose_name='超时时间(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='api_proxy.apicategory')),
            ],
            options={
                'verbose_name': 'API端点',
                'verbose_name_plural': 'API端点',
                'db_table': 'api_endpoints',
                'ordering': ['category', 'path'],
            },
        ),
    ]
