# Generated by Django 4.2.30 on 2026-05-05 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_proxy', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiendpoint',
            name='category',
        ),
        migrations.RemoveField(
            model_name='apiaccesslog',
            name='endpoint',
        ),
        migrations.DeleteModel(
            name='APICategory',
        ),
        migrations.DeleteModel(
            name='APIEndpoint',
        ),
    ]
