# Generated by Django 4.2.30 on 2026-05-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proxy', '0004_add_token_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='apichannel',
            name='remaining_quota',
            field=models.BigIntegerField(blank=True, help_text='null表示无限制', null=True, verbose_name='剩余配额'),
        ),
    ]
