# Generated by Django 4.2.30 on 2026-05-05 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0002_add_upstream_accounts'),
        ('api_proxy', '0005_add_remaining_quota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelhealthlog',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='modelchannelbinding',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='modelchannelbinding',
            name='model',
        ),
        migrations.AddField(
            model_name='apiaccesslog',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='ai_models.aimodel', verbose_name='模型'),
        ),
        migrations.AddField(
            model_name='apiaccesslog',
            name='upstream_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='ai_models.upstreamaccount', verbose_name='上游账号'),
        ),
        migrations.DeleteModel(
            name='APIChannel',
        ),
        migrations.DeleteModel(
            name='ChannelHealthLog',
        ),
        migrations.DeleteModel(
            name='ModelChannelBinding',
        ),
    ]
