# Generated by Django 4.2.30 on 2026-05-06 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_proxy', '0006_add_model_upstream_to_access_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='新对话', max_length=200, verbose_name='标题')),
                ('model_code', models.CharField(blank=True, default='', max_length=128, verbose_name='使用模型')),
                ('system_prompt', models.TextField(blank=True, default='', verbose_name='系统提示')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('last_message_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='最近消息时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI对话会话',
                'verbose_name_plural': 'AI对话会话',
                'db_table': 'chat_conversations',
                'ordering': ['-is_pinned', '-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'system'), ('user', 'user'), ('assistant', 'assistant')], max_length=16, verbose_name='角色')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('model_code', models.CharField(blank=True, default='', max_length=128, verbose_name='模型')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='提示tokens')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='回复tokens')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总tokens')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api_proxy.conversation', verbose_name='会话')),
            ],
            options={
                'verbose_name': 'AI对话消息',
                'verbose_name_plural': 'AI对话消息',
                'db_table': 'chat_messages',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
