# Generated by Django 4.2.30 on 2026-05-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proxy', '0007_conversation_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='usage_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='用量明细'),
        ),
    ]
