# Generated by Django 4.2.30 on 2026-05-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proxy', '0008_chatmessage_usage_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaccesslog',
            name='cached_tokens',
            field=models.IntegerField(default=0, verbose_name='缓存命中Token'),
        ),
        migrations.AddField(
            model_name='apiaccesslog',
            name='cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='费用(元)'),
        ),
        migrations.AddField(
            model_name='apiaccesslog',
            name='input_tokens',
            field=models.IntegerField(default=0, verbose_name='输入Token'),
        ),
        migrations.AddField(
            model_name='apiaccesslog',
            name='output_tokens',
            field=models.IntegerField(default=0, verbose_name='输出Token'),
        ),
        migrations.AddField(
            model_name='apiaccesslog',
            name='total_tokens',
            field=models.IntegerField(default=0, verbose_name='总Token'),
        ),
    ]
