# Generated by Django 4.2.30 on 2026-05-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proxy', '0009_add_token_cost_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='reasoning_content',
            field=models.TextField(blank=True, default='', help_text='推理类模型（如 DeepSeek-R1 / o1）的思维链内容', verbose_name='思考过程'),
        ),
    ]
