# Generated by Codex on 2026-05-10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0002_add_upstream_accounts'),
        ('api_proxy', '0010_add_reasoning_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='渠道名称')),
                ('base_url', models.URLField(max_length=500, verbose_name='基础URL')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API Key')),
                ('api_secret', models.CharField(blank=True, max_length=500, verbose_name='API Secret')),
                ('protocol', models.CharField(
                    choices=[('openai', 'OpenAI兼容'), ('anthropic', 'Anthropic'), ('gemini', 'Gemini')],
                    default='openai', max_length=20, verbose_name='协议',
                )),
                ('weight', models.IntegerField(
                    choices=[(1, '低权重 (1)'), (2, '中权重 (2)'), (3, '高权重 (3)')],
                    default=1, verbose_name='权重',
                )),
                ('status', models.CharField(
                    choices=[('active', '正常'), ('disabled', '已禁用'), ('maintenance', '维护中'), ('error', '异常')],
                    default='active', max_length=20, verbose_name='状态',
                )),
                ('max_qps', models.IntegerField(default=100, verbose_name='最大QPS')),
                ('max_tpm', models.IntegerField(default=100000, verbose_name='最大TPM(每分钟)')),
                ('timeout', models.IntegerField(default=120, verbose_name='超时时间(秒)')),
                ('total_calls', models.BigIntegerField(default=0, verbose_name='总调用次数')),
                ('success_rate', models.FloatField(default=100.0, verbose_name='成功率')),
                ('avg_latency', models.IntegerField(default=0, verbose_name='平均延迟(ms)')),
                ('remaining_quota', models.BigIntegerField(blank=True, help_text='null表示无限制', null=True, verbose_name='剩余配额')),
                ('priority', models.IntegerField(default=100, verbose_name='优先级')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认渠道')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('provider', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='channels', to='ai_models.modelprovider', verbose_name='模型供应商',
                )),
            ],
            options={
                'verbose_name': 'API渠道',
                'verbose_name_plural': 'API渠道',
                'ordering': ['priority', '-weight'],
            },
        ),
        migrations.CreateModel(
            name='ChannelHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(verbose_name='状态码')),
                ('response_time', models.IntegerField(verbose_name='响应时间(ms)')),
                ('is_success', models.BooleanField(verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='检查时间')),
                ('channel', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='health_logs', to='api_proxy.apichannel',
                )),
            ],
            options={
                'verbose_name': '渠道健康日志',
                'verbose_name_plural': '渠道健康日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelChannelBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('priority', models.IntegerField(default=100, verbose_name='优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('channel', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='model_bindings', to='api_proxy.apichannel',
                )),
                ('model', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='channel_bindings', to='ai_models.aimodel',
                )),
            ],
            options={
                'verbose_name': '模型渠道绑定',
                'verbose_name_plural': '模型渠道绑定',
                'ordering': ['priority'],
            },
        ),
    ]
