# Generated by Django 6.0.4 on 2026-05-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_proxy", "0011_apichannel_protocol"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiaccesslog",
            name="profit",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                help_text="用户支付费用与上游成本的差额",
                max_digits=12,
                verbose_name="利润(元)",
            ),
        ),
        migrations.AddField(
            model_name="apiaccesslog",
            name="upstream_cost",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                help_text="实际支付给上游供应商的费用",
                max_digits=12,
                verbose_name="上游成本(元)",
            ),
        ),
    ]
