# Generated by Django 4.2.30 on 2026-05-05 10:19

import apps.tickets.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.tickets.models.ticket_image_upload_path,
                        verbose_name="图片",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "file_size",
                    models.IntegerField(default=0, verbose_name="文件大小(字节)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="tickets.ticketreply",
                        verbose_name="回复",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="tickets.ticket",
                        verbose_name="工单",
                    ),
                ),
            ],
            options={
                "verbose_name": "工单图片",
                "verbose_name_plural": "工单图片",
                "db_table": "ticket_images",
                "ordering": ("created_at",),
            },
        ),
    ]
