# Generated by Django 4.2.30 on 2026-05-04 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='分类代码')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '模型分类',
                'verbose_name_plural': '模型分类',
                'db_table': 'model_categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='供应商名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='供应商代码')),
                ('logo', models.URLField(blank=True, verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='官网')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '模型供应商',
                'verbose_name_plural': '模型供应商',
                'db_table': 'model_providers',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模型名称')),
                ('code', models.CharField(max_length=100, verbose_name='模型代码')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='版本')),
                ('input_price', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='输入价格(元/千tokens)')),
                ('output_price', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='输出价格(元/千tokens)')),
                ('supports_streaming', models.BooleanField(default=True, verbose_name='支持流式')),
                ('supports_vision', models.BooleanField(default=False, verbose_name='支持视觉')),
                ('supports_tools', models.BooleanField(default=False, verbose_name='支持工具调用')),
                ('supports_json', models.BooleanField(default=False, verbose_name='支持JSON模式')),
                ('context_window', models.IntegerField(default=4096, verbose_name='上下文窗口')),
                ('max_tokens', models.IntegerField(default=2048, verbose_name='最大输出tokens')),
                ('description', models.TextField(blank=True, verbose_name='模型描述')),
                ('capabilities', models.JSONField(blank=True, default=list, verbose_name='能力标签')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('status', models.CharField(choices=[('active', '已上架'), ('inactive', '已下架'), ('beta', '测试中')], default='active', max_length=20, verbose_name='状态')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否新品')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='评分')),
                ('api_endpoint', models.CharField(blank=True, max_length=500, verbose_name='API端点')),
                ('api_model_id', models.CharField(blank=True, max_length=200, verbose_name='API模型ID')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='ai_models.modelcategory', verbose_name='分类')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai_models.modelprovider', verbose_name='供应商')),
            ],
            options={
                'verbose_name': 'AI模型',
                'verbose_name_plural': 'AI模型',
                'db_table': 'ai_models',
                'ordering': ['-is_featured', 'order', '-created_at'],
                'unique_together': {('provider', 'code')},
            },
        ),
    ]
