# Generated by Django 4.2.30 on 2026-05-05 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpstreamAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='账号名称')),
                ('base_url', models.CharField(help_text='如: https://api.openai.com/v1', max_length=500, verbose_name='API基础地址')),
                ('api_key', models.CharField(max_length=500, verbose_name='API密钥')),
                ('proxy_url', models.CharField(blank=True, help_text='留空则直连', max_length=500, verbose_name='代理地址')),
                ('max_rpm', models.IntegerField(default=60, verbose_name='最大请求速率(次/分钟)')),
                ('max_tpm', models.IntegerField(default=100000, verbose_name='最大Token速率(次/分钟)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_available', models.BooleanField(default=True, help_text='自动检测，宕机时自动标记', verbose_name='是否可用')),
                ('last_error', models.TextField(blank=True, verbose_name='最近错误')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_accounts', to='ai_models.modelprovider', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '上游账号',
                'verbose_name_plural': '上游账号',
                'db_table': 'upstream_accounts',
                'ordering': ['-is_active', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModelUpstreamAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1, help_text='权重越高，被选中的概率越大', verbose_name='权重')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('error_count', models.IntegerField(default=0, verbose_name='错误次数')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='上次使用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_bindings', to='ai_models.upstreamaccount', verbose_name='上游账号')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_accounts', to='ai_models.aimodel', verbose_name='模型')),
            ],
            options={
                'verbose_name': '模型账号关联',
                'verbose_name_plural': '模型账号关联',
                'db_table': 'model_upstream_accounts',
                'unique_together': {('model', 'account')},
            },
        ),
    ]
