# Generated by Django 4.2.30 on 2026-05-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0002_add_upstream_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='cached_input_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='输入 tokens 中命中缓存部分的单价；为 0 时按 input_price 计费', max_digits=12, verbose_name='缓存命中价格(元/百万tokens)'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='input_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='输入价格(元/百万tokens)'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='output_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='输出价格(元/百万tokens)'),
        ),
    ]
