# Generated by Codex on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0004_scale_prices_to_million_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstreamaccount',
            name='protocol',
            field=models.CharField(
                choices=[
                    ('openai', 'OpenAI兼容'),
                    ('anthropic', 'Anthropic'),
                    ('gemini', 'Gemini'),
                ],
                default='openai',
                max_length=20,
                verbose_name='协议',
            ),
        ),
    ]
