# Generated by Django 6.0.4 on 2026-05-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0005_upstreamaccount_protocol"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelupstreamaccount",
            name="cost_cached_input_price",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="上游供应商对该模型缓存命中部分的单价；为0时按 cost_input_price 计",
                max_digits=12,
                verbose_name="上游缓存输入成本(元/百万tokens)",
            ),
        ),
        migrations.AddField(
            model_name="modelupstreamaccount",
            name="cost_input_price",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="上游供应商对该模型在此账号下的输入单价",
                max_digits=12,
                verbose_name="上游输入成本(元/百万tokens)",
            ),
        ),
        migrations.AddField(
            model_name="modelupstreamaccount",
            name="cost_output_price",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="上游供应商对该模型在此账号下的输出单价",
                max_digits=12,
                verbose_name="上游输出成本(元/百万tokens)",
            ),
        ),
    ]
