# Generated by Django 6.0.4 on 2026-05-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0006_add_cost_profit_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="per_image_price",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="图像生成类模型的单张价格",
                max_digits=10,
                verbose_name="单张图片价格(元)",
            ),
        ),
    ]
